spring:
  application:
    name: ds
  datasource:
    url: jdbc:mysql://localhost:3306/d42-api-pdc
    username: apiUser
    password: late%37

server:
  port: 8080
  servlet:
    context-path: /ds
  shutdown: graceful

logging:
  file:
    name: logs/trace.log